name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: virtualzone
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    - name: Register binfmt_misc entry for qemu-user-static
      run: |
        docker run --rm --privileged --volume qemu-user-static:/usr/bin:ro multiarch/qemu-user-static:register --reset
    - name: Build and push amd64
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          virtualzone/compose-updater:amd64
          virtualzone/compose-updater:latest
    - name: Build and push arm32v7
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.arm32v7
        push: true
        tags: |
          virtualzone/compose-updater:arm32v7
    - name: Build and push arm32v6
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.arm32v6
        push: true
        tags: |
          virtualzone/compose-updater:arm32v6
    - name: Build and push arm64v8
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.arm64v8
        push: true
        tags: |
          virtualzone/compose-updater:arm64v8
    - name: Create multi-arch latest image
      run: |
        curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
        chmod +x manifest-tool
        ./manifest-tool push from-spec multi-arch-manifest.yaml